# Generated by Django 3.0.4 on 2020-03-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimereport',
            fields=[
                ('acknowledgement_no', models.TextField(db_column='Acknowledgement_No', primary_key=True, serialize=False, verbose_name='Acknowledgement No')),
                ('district', models.TextField(blank=True, db_column='District', null=True)),
                ('police_station', models.TextField(blank=True, db_column='Police_Station', null=True)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('sub_category', models.TextField(blank=True, db_column='Sub_Category', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('incident_date', models.TextField(blank=True, db_column='Incident_Date', null=True)),
                ('complaint_date', models.TextField(blank=True, db_column='Complaint_Date', null=True)),
                ('last_action_taken_on', models.TextField(blank=True, db_column='Last_Action_Taken_on', null=True)),
            ],
            options={
                'db_table': 'CrimeReport',
                'managed': True,
            },
        ),
    ]
