# Generated by Django 3.0.4 on 2020-03-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='acknowledgement_no',
            field=models.TextField(db_column='Acknowledgement_No', primary_key=True, serialize=False),
        ),
    ]
