# Generated by Django 3.0.4 on 2020-03-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0003_auto_20200309_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='complaint_date',
            field=models.CharField(blank=True, db_column='Complaint_Date', max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='incident_date',
            field=models.CharField(blank=True, db_column='Incident_Date', max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='last_action_taken_on',
            field=models.CharField(blank=True, db_column='Last_Action_Taken_on', max_length=264, null=True),
        ),
    ]
