# Generated by Django 3.0.4 on 2020-03-09 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0005_auto_20200309_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='complaint_date',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='last_action_taken_on',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='Complaint_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crimereport',
            name='Incident_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crimereport',
            name='Last_Action_Taken_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
