# Generated by Django 3.0.4 on 2020-03-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0006_auto_20200309_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimereport',
            old_name='Complaint_Date',
            new_name='complaint_date',
        ),
        migrations.RenameField(
            model_name='crimereport',
            old_name='Incident_Date',
            new_name='incident_date',
        ),
        migrations.RenameField(
            model_name='crimereport',
            old_name='Last_Action_Taken_on',
            new_name='last_action_taken_on',
        ),
    ]
