# Generated by Django 3.0.4 on 2020-03-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0008_auto_20200309_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='last_action_taken_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
